export enum GameType {
  SHADOWRUN = "shadowrun",
  VAMPIRE_THE_MASQUERADE = "vampire_the_masquerade",
  CALL_OF_CTHULHU = "call_of_cthulhu",
  SEVENTH_SEA = "seventh_sea",
  EXPANSE = "expanse",
  SLAVIC = "slavic",
  DRAGONLANCE = "dragonlance",
  CUSTOM = "custom",
}

export enum TtsVoice {
  Callum = "Callum",
  CaraGee = "CaraGee",
  JoeyCocoDiaz = "JoeyCocoDiaz",
  MelHudson = "MelHudson",
  ShohrehAghdashloo = "ShohrehAghdashloo",
  StephenFry = "StephenFry",
  DavidStrathairn = "DavidStrathairn",
  Drummer = "Drummer",
  NeilGaiman = "NeilGaiman",
  LeonardNimoy = "LeonardNimoy",
  RayPorter = "RayPorter",
  JasonCarl = "JasonCarl",
  PoE2_Witch = "PoE2_Witch",
  PoE2_Shambrin = "PoE2_Shambrin",
  PoE2_Servi = "PoE2_Servi",
  PoE2_Doryani = "PoE2_Doryani",
  PoE2_Tavakai = "PoE2_Tavakai",
  Cyberpunk_Brigitte = "Cyberpunk_Brigitte",
}
